import React from 'react';

const masterCompanyList = [
    {
      companyName: "Corporate Crime Control Association",
      coreServices: [
        "Patrol",
        "Loss Prevention",
        "Entry Access",
        "Surveilance",
        "Event Security",
        "Executive/Personnel Protection",
        "Estate and Residential Protection",
        "Security Consulting",
      ],
      specialServices: [
        "Transient Disbursement Services",
        "Street Crime Unit",
        "Drone Services (Day and Night FLIR)",
        "Executive Protection",
        "Workplace Violence Details",
        "Mobile Incident Command Center",
        "Security Training",
        "Private Investigation",
      ],
      discreet: true,
      armedServices: true,
      handsOn: true,
      hourlyRange: "med",
      contactNumber: "(503)-951-0903",
      address: "21328 Highway 99E Aurora, OR 97002",
      coordinates: [45.357309,-122.608271],
      url: "http://www.corporatecrimecontrol.com/",
  
    },
    {
      companyName: "Northwest Enforcement",
      coreServices: [
        "Patrol",
        "Loss Prevention",
        "Entry Access",
        "Surveilance",
        "Event Security",
        "Executive/Personnel Protection",
        "Estate and Residential Protection",
        "Secure Transport",
      ],
      specialServices: [
        "Security Training",
      ],
      discreet: true,
      armedServices: true,
      handsOn: true,
      hourlyRange: "med",
      contactNumber: "503-893-8858",
      address: "17116 NE Sandy Blvd, Portland, OR 97230",
      coordinates: [45.32505,-122.29130],
      url: "http://nwenforcement.com/",
  
    },
    {
      companyName: "Securitas",
      coreServices: [
        "Loss Prevention",
        "Entry Access",
        "Surveilance",
        "Event Security",
        "Executive/Personnel Protection",
        "Estate and Residential Protection",
      ],
      specialServices: [
        "Fire and Safety Services",
        "Electronic Security",
      ],
      discreet: false,
      armedServices: false,
      handsOn: false,
      hourlyRange: "low",
      contactNumber: "503.243.1620",
      address: "129 SW 4th Ave, Portland, OR 97204",
      coordinates: [45.31191,-122.40296],
      url: "https://www.securitasinc.com/Contact-Us/Oregon/Portland/"
  
    },
    {
      companyName: "Sharpe Security Services",
      coreServices: [
        "Security Consulting",
      ],
      specialServices: [
        "Security Training",
      ],
      discreet: false,
      armedServices: true,
      handsOn: true,
      hourlyRange: "high",
      contactNumber: "(503)-575-8537",
      address: "9880 SW Beaverton Hillsdale HWY, STE 103 Beaverton, OR 97005",
      coordinates: [45.29105,-122.46419],
      url: "http://www.sharpepdx.com",
  
    },
    {
      companyName: "Black Wolf Protection Group",
      coreServices: [
        "Patrol",
        "Entry Access",
        "Event Security",
        "Executive/Personnel Protection",
        "Estate and Residential Protection",
        "Security Consulting",
      ],
      specialServices: [
        "Executive Protection",
        "Private Investigation",
      ],
      discreet: true,
      armedServices: true,
      handsOn: true,
      hourlyRange: "med",
      contactNumber: "(971) 334-6023",
      address: "Address N/A",
      coordinates: null,
      url: "https://blackwolfprotectiongroup.com"
  
    },
    {
      companyName: "Pacific Armored",
      coreServices: [
        "Secure Transport",
      ],
      specialServices: [
        "ATM Services",
      ],
      discreet: true,
      armedServices: true,
      handsOn: true,
      hourlyRange: "med",
      contactNumber: "503-454-0511",
      address: "11507 SW Shilo Ln C, Portland, OR 97225",
      coordinates: [45.30553,-122.47772],
      url: "https://www.pacificarmored.com/atm-servicing/",
    },
    {
      companyName: "Bear Arms Security (Armed ONLY)",
      coreServices: [
        "Patrol",
        "Loss Prevention",
        "Entry Access",
        "Surveilance",
        "Event Security",
        "Executive/Personnel Protection",
        "Estate and Residential Protection",
        "Security Consulting",
        "Alarm Response",
      ],
      specialServices: [
        "Active Shooter Response",
        "Corporate Security Plan Development",
        "Executive Protection",
        "Public Emergency Response",
        "Security Training",
        "Crime Scene/Disaster Recovery Security",
      ],
      discreet: true,
      armedServices: true,
      handsOn: true,
      hourlyRange: "high",
      contactNumber: "(503) 320-9421",
      address: "7609 SE Overland St, Portland, OR 97222",
      coordinates: [45.27164,-122.35065],
      url: "https://www.beararmssecurity.com/",
  
    },
    {
      companyName: "Metro Watch",
      coreServices: [
        "Patrol",
        "Entry Access",
        "Event Security",
        "Estate and Residential Protection",
        "Alarm Response",
      ],
      specialServices: [
      ],
      discreet: false,
      armedServices: false,
      handsOn: false,
      hourlyRange: "med",
      contactNumber: "(503) 226-6561",
      address: "4501 NE Minnehaha St Ste 100, Vancouver, WA 98661",
      coordinates: [45.40029,-122.37312],
      url: "https://www.metro-watch.com",
  
    },
    {
      companyName: "G4S Secure Solutions",
      coreServices: [
        "Entry Access",
        "Surveilance",
        "Event Security",
        "Executive/Personnel Protection",
        "Estate and Residential Protection",
        "Security Consulting",
      ],
      specialServices: [
        "Software and Technology",
        "Nuclear and Critical Infrastructure Experience",
        "Executive Protection",
        "Private Investigation",
      ],
      discreet: true,
      armedServices: true,
      handsOn: true,
      hourlyRange: "med",
      contactNumber: "(503)-951-0903",
      address: "5100 SW Macadam Ave South Portland",
      coordinates: [45.29095,-122.40308],
      url: "https://www.g4s.com/en-us/contact-us/local-offices/portland",
  
    },
    {
      companyName: "Portland Patrol",
      coreServices: [
        "Patrol",
        "Surveilance",
        "Alarm Response",
      ],
      specialServices: [
        
      ],
      discreet: false,
      armedServices: true,
      handsOn: true,
      hourlyRange: "med",
      contactNumber: "(503)-224-7383",
      address: "208 NW First Ave Portland, OR 97209",
      coordinates: [45.31298,-122.40151],
      url: "https://portlandpatrol.com/",
  
    },
    {
      companyName: "Advanced Security",
      coreServices: [
        "Patrol",
        "Entry Access",
        "Surveilance",
        "Event Security",
        "Executive/Personnel Protection",
        "Estate and Residential Protection",
        "Alarm Response",
      ],
      specialServices: [
        "Executive Protection",
        "Workplace Violence Details",
        
      ],
      discreet: false,
      armedServices: true,
      handsOn: true,
      hourlyRange: "med",
      contactNumber: "503-222-5381",
      address: "716 SE 11th Avenue Suite A Portland, OR 97214",
      coordinates: [45.517573,-122.654422],
      url: "https://www.advancedsecurityinc.com/",
  
    },
    {
      companyName: "Eclipse Security",
      coreServices: [
        "Patrol",
        "Loss Prevention",
        "Entry Access",
        "Surveilance",
        "Event Security",
        "Executive/Personnel Protection",
        "Estate and Residential Protection",
        "Security Consulting",
        "Alarm Response",
      ],
      specialServices: [
        "Transient Disbursement Services",
        "Executive Protection",
        "Workplace Violence Details",
        "Security Training",
        "Private Investigation",
        
        "Crowd Control",
      ],
      discreet: true,
      armedServices: true,
      handsOn: true,
      hourlyRange: "med",
      contactNumber: "503-454-0997",
      address: "11118 NE Halsey St Portland, OR 97220",
      coordinates: [45.533226, -122.548175],
      url: "http://www.eclipse-security-service.com/",
  
    },
  ]

  export default masterCompanyList